### ISSUE TITLE
Updated version for Angular 4

### ISSUE THREAD

**Issue by PeterOscarsson** [D3Automation/angular2-c360-sample#6]
Hi. 
Is there any plans to update this project to Angular 4 and other new dependencies

Best regards 
Peter

**Comment by bencameron** [comment]
@PeterOscarsson - To be honest, we didn't realize that anyone was using it.  :) We've moved on from C360 for our own work, but I'd be happy to put some time into upgrading this project to the latest version of Angular.  I should have some time in the next week or two.

**Comment by PeterOscarsson** [comment]
@bencameron , Well we are a small development shop and we have just received an assignment to make a small website around c360, with login and some other small parts regarding file download. We are doing some angular4 work and found this library and thought it would make life easier for us.  

If you have time to upgrade it, I would be very happy, else I have to cherrypick some parts to our app.

Just out of curiosity, if you left c360, may I ask why and where, as it looks like we may get some more assignments regarding this kind of integration with C360.

/Peter
Impleo

**Comment by bencameron** [comment]
@PeterOscarsson - I apologize for moving so slowly on this.  I've been swamped and haven't had a chance to get to it.  I'd be happy to accept a PR if you're up for doing the work, but I'd also be fine with you cherrypicking the pieces you need as you mentioned above.

Regarding C360, we left due to some challenges we were having developing against it.  We found that it could be a good fit for automating a single part or relatively simple assembly, but most of the projects we work on involve automating large, complex assemblies.  We had a little bit of luck in making that work using the ETO language, but the performance was terrible, logging/diagnostics were not helpful, and deployment of code changes was a real pain.  After Autodesk announced the end of ETO, we decided to abandon it altogether.

We are now using a .NET Core-based rules engine that we developed in-house.  We use an Angular-based front-end to manipulate the model and display simplified graphics (huge performance benefit) that are kept in sync with the model.  We then send the configuration to a separate service for generating full-detail CAD models.

**Comment by PeterOscarsson** [comment]
@bencameron Thanx for your reply. We have already cherry-picked and made our own Angular Interface.  Its part of a larger application and as always there is no time to create a standalone version.

Thanx also for your Input on C360. We have also seen some problems but I think everything is working as planned now for the 2 projects we have.
